name: PerWorldChat
version: ${version}
main: lol.hyper.perworldchat.PerWorldChat
api-version: '26.1.1'
load: STARTUP
author: hyperdefined
website: https://github.com/hyperdefined/PerWorldChat/
description: Separate chat between worlds.
folia-supported: true

loader: lol.hyper.perworldchat.PerWorldChatLoader

commands:
  worlds:
    usage: /worlds