name: PerWorldChat
version: ${project.version}
main: lol.hyper.perworldchat.PerWorldChat
api-version: 1.13
load: STARTUP
author: hyperdefined
website: https://www.spigotmc.org/resources/perworldchat.94282/
description: Separate chat between worlds.
commands:
  worlds:
    usage: /worlds
libraries:
  - lol.hyper:github-release-api:1.0.1
  - net.kyori:adventure-text-minimessage:4.11.0
  - net.kyori:adventure-platform-bukkit:4.1.0