name: PerWorldChat
version: ${project.version}
main: lol.hyper.perworldchat.PerWorldChat
api-version: 1.21
load: STARTUP
author: hyperdefined
website: https://github.com/hyperdefined/PerWorldChat/
description: Separate chat between worlds.
folia-supported: true
commands:
  worlds:
    usage: /worlds