name: PerWorldChat
version: ${project.version}
main: lol.hyper.perworldchat.PerWorldChat
api-version: 1.13
load: STARTUP
author: hyperdefined
website: https://www.spigotmc.org/resources/perworldchat.94282/
description: Separate chat between worlds.
folia-supported: true
commands:
  worlds:
    usage: /worlds